# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9ab1b4aff5c8294d97c423ce708c2953"
name = "Startiv App"
handle = "startiv-app"
application_url = "https://winning-limit-tmp-mauritius.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://winning-limit-tmp-mauritius.trycloudflare.com/auth/callback", "https://winning-limit-tmp-mauritius.trycloudflare.com/auth/shopify/callback", "https://winning-limit-tmp-mauritius.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
